



//AUTOGENERATED, DO NOTMODIFY.
//Do not edit this file directly.

using System;
using RethinkDb.Driver.Model;
using RethinkDb.Driver.Ast;

namespace RethinkDb.Driver {
    public class ReqlOpIndeterminateError : ReqlAvailabilityError {


        public ReqlOpIndeterminateError () {
        }

        public ReqlOpIndeterminateError (Exception e) : this(e.Message, e) {
        }

        public ReqlOpIndeterminateError (string message) : base(message)
        {
        }

        public ReqlOpIndeterminateError (string message, Exception innerException) : base(message, innerException)
        {
        }
        
        
    }
}
