



//AUTOGENERATED, DO NOTMODIFY.
//Do not edit this file directly.

using System;
using RethinkDb.Driver.Model;
using RethinkDb.Driver.Ast;

namespace RethinkDb.Driver {
    public class ReqlUserError : ReqlRuntimeError {


        public ReqlUserError () {
        }

        public ReqlUserError (Exception e) : this(e.Message, e) {
        }

        public ReqlUserError (string message) : base(message)
        {
        }

        public ReqlUserError (string message, Exception innerException) : base(message, innerException)
        {
        }
        
        
    }
}
