



//AUTOGENERATED, DO NOTMODIFY.
//Do not edit this file directly.

using System;
using RethinkDb.Driver.Model;
using RethinkDb.Driver.Ast;

namespace RethinkDb.Driver {
    public class ReqlError : Exception {

            public Backtrace Backtrace { get; set; }
            public ReqlAst Term { get; set; }

        public ReqlError () {
        }

        public ReqlError (Exception e) : this(e.Message, e) {
        }

        public ReqlError (string message) : base(message)
        {
        }

        public ReqlError (string message, Exception innerException) : base(message, innerException)
        {
        }
        
        
    }
}
