



//AUTOGENERATED, DO NOTMODIFY.
//Do not edit this file directly.

using System;
using RethinkDb.Driver.Model;
using RethinkDb.Driver.Ast;

namespace RethinkDb.Driver {
    public class ReqlDriverError : ReqlError {


        public ReqlDriverError () {
        }

        public ReqlDriverError (Exception e) : this(e.Message, e) {
        }

        public ReqlDriverError (string message) : base(message)
        {
        }

        public ReqlDriverError (string message, Exception innerException) : base(message, innerException)
        {
        }
        
        
    }
}
