#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Templates.CodeGen.Specialized
{
    using System;
    
    #line 2 "..\..\CodeGen\Specialized\Datum.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 3 "..\..\CodeGen\Specialized\Datum.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 4 "..\..\CodeGen\Specialized\Datum.cshtml"
    using Humanizer;
    
    #line default
    #line hidden
    
    #line 5 "..\..\CodeGen\Specialized\Datum.cshtml"
    using Newtonsoft.Json.Linq;
    
    #line default
    #line hidden
    
    #line 6 "..\..\CodeGen\Specialized\Datum.cshtml"
    using Templates.CodeGen;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class Datum : AstSubclassTemplate
    {
#line hidden

        #line 32 "..\..\CodeGen\Specialized\Datum.cshtml"

    

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");






WriteLiteral("\r\n");


WriteLiteral("\r\n");


            
            #line 10 "..\..\CodeGen\Specialized\Datum.cshtml"
  
    this.Layout = UseParentLayout(this);


            
            #line default
            #line hidden
WriteLiteral("\r\n");


DefineSection("Ctors", () => {

WriteLiteral("\r\n    public Datum(object arg) : base(TermType.DATUM, null, null) {\r\n            " +
"datum = arg;\r\n        }\r\n");


});

WriteLiteral("\r\n");


DefineSection("StaticFactories", () => {

WriteLiteral("\r\n    \r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("SpecialMethods", () => {

WriteLiteral("\r\n    \r\n        protected internal override object Build() {\r\n            // Over" +
"ridden because Datums are leaf-nodes and therefore\r\n            // don\'t contain" +
" lower ReqlAst objects.\r\n            return datum;\r\n        }\r\n");


});

WriteLiteral("\r\n\r\n");


WriteLiteral("\r\n       \r\n        internal object datum;\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
