#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Templates.CodeGen.Specialized
{
    using System;
    
    #line 2 "..\..\CodeGen\Specialized\Func.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 3 "..\..\CodeGen\Specialized\Func.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 4 "..\..\CodeGen\Specialized\Func.cshtml"
    using Humanizer;
    
    #line default
    #line hidden
    
    #line 5 "..\..\CodeGen\Specialized\Func.cshtml"
    using Newtonsoft.Json.Linq;
    
    #line default
    #line hidden
    
    #line 6 "..\..\CodeGen\Specialized\Func.cshtml"
    using Templates;
    
    #line default
    #line hidden
    
    #line 7 "..\..\CodeGen\Specialized\Func.cshtml"
    using Templates.CodeGen;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class Func : AstSubclassTemplate
    {
#line hidden

        #line 124 "..\..\CodeGen\Specialized\Func.cshtml"

    

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");







WriteLiteral("\r\n");


WriteLiteral("\r\n");


            
            #line 11 "..\..\CodeGen\Specialized\Func.cshtml"
  
    this.Layout = UseParentLayout(this);


            
            #line default
            #line hidden
WriteLiteral("\r\n");


DefineSection("Add_Imports", () => {

WriteLiteral("\r\n    using System.Threading;\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("Ctors", () => {

WriteLiteral("\r\n    \r\n        protected Func(Arguments args) : base(TermType.FUNC, args, null)\r" +
"\n        {\r\n        }\r\n\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("MemberVars", () => {

WriteLiteral("\r\n        private static int VarId = 0;\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("SpecialMethods", () => {

WriteLiteral("\r\n        internal static int NextVarId(){\r\n            return Interlocked.Increm" +
"ent(ref VarId);\r\n        }\r\n        internal static Guid NextVarGuid(){\r\n       " +
"     return Guid.NewGuid();\r\n        }\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("StaticFactories", () => {

WriteLiteral("\r\n    \r\n    \r\n    public static Func FromLambda(Delegate function){\r\n    \r\n      " +
"  if( function is ReqlFunction0 func0 )\r\n        {\r\n            return new Func(" +
"Arguments.Make(new List<object>(),\r\n                Util.ToReqlAst( func0() )));" +
"\r\n        }\r\n");


            
            #line 50 "..\..\CodeGen\Specialized\Func.cshtml"
         foreach( var n in Enumerable.Range(1, GeneratorForAst.GetMaxArity()) )
        {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("//Function ");


            
            #line 52 "..\..\CodeGen\Specialized\Func.cshtml"
                    Write(n);

            
            #line default
            #line hidden
WriteLiteral("\r\n");



WriteLiteral("            ");

WriteLiteral("if( function is ");


            
            #line 53 "..\..\CodeGen\Specialized\Func.cshtml"
                          Write("ReqlFunction" + n);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 53 "..\..\CodeGen\Specialized\Func.cshtml"
                                                Write("func"+n);

            
            #line default
            #line hidden
WriteLiteral(" ){\r\n");


            
            #line 54 "..\..\CodeGen\Specialized\Func.cshtml"
                for( int v = 1; v <= n; v++ )
                {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("int ");


            
            #line 56 "..\..\CodeGen\Specialized\Func.cshtml"
                  Write("var" + v);

            
            #line default
            #line hidden
WriteLiteral(" = NextVarId();\r\n");


            
            #line 57 "..\..\CodeGen\Specialized\Func.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("var varIds = new List<int>{ \r\n");


            
            #line 59 "..\..\CodeGen\Specialized\Func.cshtml"
                for( int v = 1; v <= n; v++ )
                {

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral("var");


            
            #line 61 "..\..\CodeGen\Specialized\Func.cshtml"
                     Write(v + ",");

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 62 "..\..\CodeGen\Specialized\Func.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("};\r\n");


            
            #line 64 "..\..\CodeGen\Specialized\Func.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("var appliedFunction = ");


            
            #line 65 "..\..\CodeGen\Specialized\Func.cshtml"
                                    Write("func"+n);

            
            #line default
            #line hidden
WriteLiteral("(\r\n");


            
            #line 66 "..\..\CodeGen\Specialized\Func.cshtml"
                    for (int v = 1; v <= n; v++)
                {

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral("new Var(var");


            
            #line 68 "..\..\CodeGen\Specialized\Func.cshtml"
                             Write(v);

            
            #line default
            #line hidden
WriteLiteral(") ");


            
            #line 68 "..\..\CodeGen\Specialized\Func.cshtml"
                                   Write(v == n ? "" : ",");

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 69 "..\..\CodeGen\Specialized\Func.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral(");\r\n");


            
            #line 71 "..\..\CodeGen\Specialized\Func.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("return new Func(Arguments.Make(\r\n");



WriteLiteral("                        ");

WriteLiteral("new MakeArray(varIds),\r\n");



WriteLiteral("                        ");

WriteLiteral("Util.ToReqlAst(appliedFunction)\r\n");



WriteLiteral("                ");

WriteLiteral("));\r\n");



WriteLiteral("            ");

WriteLiteral("}\r\n");


            
            #line 77 "..\..\CodeGen\Specialized\Func.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral(@"    
        throw new ReqlDriverError(""Arity of ReqlLambda not recognized!"");
    }
    
    public static Func Serialize(Delegate function, List<Guid> context){
    
        if( function is ReqlFunction0 func0 )
        {
            return new Func(Arguments.Make(new List<object>(),
                Util.ToReqlAst( func0() )));
        }
");


            
            #line 89 "..\..\CodeGen\Specialized\Func.cshtml"
         foreach( var n in Enumerable.Range(1, GeneratorForAst.GetMaxArity()) )
        {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("//Function ");


            
            #line 91 "..\..\CodeGen\Specialized\Func.cshtml"
                    Write(n);

            
            #line default
            #line hidden
WriteLiteral("\r\n");



WriteLiteral("            ");

WriteLiteral("if( function is ");


            
            #line 92 "..\..\CodeGen\Specialized\Func.cshtml"
                          Write("ReqlFunction" + n);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 92 "..\..\CodeGen\Specialized\Func.cshtml"
                                                Write("func" + n);

            
            #line default
            #line hidden
WriteLiteral(" ){\r\n");


            
            #line 93 "..\..\CodeGen\Specialized\Func.cshtml"
                for( int v = 1; v <= n; v++ )
                {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("Guid ");


            
            #line 95 "..\..\CodeGen\Specialized\Func.cshtml"
                   Write("var" + v);

            
            #line default
            #line hidden
WriteLiteral(" = NextVarGuid();\r\n");


            
            #line 96 "..\..\CodeGen\Specialized\Func.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("var varIds = new List<Guid>{ \r\n");


            
            #line 98 "..\..\CodeGen\Specialized\Func.cshtml"
                for( int v = 1; v <= n; v++ )
                {

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral("var");


            
            #line 100 "..\..\CodeGen\Specialized\Func.cshtml"
                     Write(v + ",");

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 101 "..\..\CodeGen\Specialized\Func.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("};\r\n");



WriteLiteral("                ");

WriteLiteral("context.AddRange(varIds);\r\n");



WriteLiteral("                ");

WriteLiteral("var appliedFunction = ");


            
            #line 104 "..\..\CodeGen\Specialized\Func.cshtml"
                                    Write("func"+n);

            
            #line default
            #line hidden
WriteLiteral("(\r\n");


            
            #line 105 "..\..\CodeGen\Specialized\Func.cshtml"
                    for (int v = 1; v <= n; v++)
                {

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral("new Var(var");


            
            #line 107 "..\..\CodeGen\Specialized\Func.cshtml"
                             Write(v);

            
            #line default
            #line hidden
WriteLiteral(") ");


            
            #line 107 "..\..\CodeGen\Specialized\Func.cshtml"
                                   Write(v == n ? "" : ",");

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 108 "..\..\CodeGen\Specialized\Func.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral(");\r\n");


            
            #line 110 "..\..\CodeGen\Specialized\Func.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("return new Func(Arguments.Make(\r\n");



WriteLiteral("                        ");

WriteLiteral("new MakeArray(varIds),\r\n");



WriteLiteral("                        ");

WriteLiteral("Util.ToReqlAst(appliedFunction)\r\n");



WriteLiteral("                ");

WriteLiteral("));\r\n");



WriteLiteral("            ");

WriteLiteral("}\r\n");


            
            #line 116 "..\..\CodeGen\Specialized\Func.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    \r\n        throw new ReqlDriverError(\"Arity of ReqlLambda not recognized!\");\r\n" +
"    }\r\n    \r\n");


});

WriteLiteral("\r\n\r\n\r\n");


WriteLiteral("\r\n       \r\n      ");


        }
    }
}
#pragma warning restore 1591
