#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Templates.CodeGen.Specialized
{
    using System;
    
    #line 2 "..\..\CodeGen\Specialized\ResponseType.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 3 "..\..\CodeGen\Specialized\ResponseType.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 4 "..\..\CodeGen\Specialized\ResponseType.cshtml"
    using Humanizer;
    
    #line default
    #line hidden
    
    #line 5 "..\..\CodeGen\Specialized\ResponseType.cshtml"
    using Newtonsoft.Json.Linq;
    
    #line default
    #line hidden
    
    #line 6 "..\..\CodeGen\Specialized\ResponseType.cshtml"
    using Templates.CodeGen;
    
    #line default
    #line hidden
    
    #line 7 "..\..\CodeGen\Specialized\ResponseType.cshtml"
    using Templates.CodeGen.Util;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class ResponseType : EnumTemplate
    {
#line hidden

        #line 15 "..\..\CodeGen\Specialized\ResponseType.cshtml"

    

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");







WriteLiteral("\r\n");


WriteLiteral("\r\n");


            
            #line 11 "..\..\CodeGen\Specialized\ResponseType.cshtml"
  
    this.Layout = UseParentLayout(this);


            
            #line default
            #line hidden
WriteLiteral("\r\n");


WriteLiteral("\r\n\r\n");


DefineSection("CustomMethods", () => {

WriteLiteral("\r\n    \r\n    public static class ResponseTypeLong{\r\n        public const long SUCC" +
"ESS_ATOM = ");


            
            #line 22 "..\..\CodeGen\Specialized\ResponseType.cshtml"
                                     Write($@"{{""t"":1,""".GetAsciiStringAsLong());

            
            #line default
            #line hidden
WriteLiteral("\r\n        public const long SUCCESS_SEQUENCE = ");


            
            #line 23 "..\..\CodeGen\Specialized\ResponseType.cshtml"
                                         Write($@"{{""t"":2,""".GetAsciiStringAsLong());

            
            #line default
            #line hidden
WriteLiteral("\r\n        public const long SUCCESS_PARTIAL =");


            
            #line 24 "..\..\CodeGen\Specialized\ResponseType.cshtml"
                                       Write($@"{{""t"":3,""".GetAsciiStringAsLong());

            
            #line default
            #line hidden
WriteLiteral("\r\n        public const long WAIT_COMPLETE = ");


            
            #line 25 "..\..\CodeGen\Specialized\ResponseType.cshtml"
                                      Write($@"{{""t"":4,""".GetAsciiStringAsLong());

            
            #line default
            #line hidden
WriteLiteral("\r\n        public const long SERVER_INFO = ");


            
            #line 26 "..\..\CodeGen\Specialized\ResponseType.cshtml"
                                    Write($@"{{""t"":5,""".GetAsciiStringAsLong());

            
            #line default
            #line hidden
WriteLiteral("\r\n        public const long CLIENT_ERROR = ");


            
            #line 27 "..\..\CodeGen\Specialized\ResponseType.cshtml"
                                     Write($@"{{""t"":16,".GetAsciiStringAsLong());

            
            #line default
            #line hidden
WriteLiteral("\r\n        public const long COMPILE_ERROR = ");


            
            #line 28 "..\..\CodeGen\Specialized\ResponseType.cshtml"
                                      Write($@"{{""t"":17,".GetAsciiStringAsLong());

            
            #line default
            #line hidden
WriteLiteral("\r\n        public const long RUNTIME_ERROR = ");


            
            #line 29 "..\..\CodeGen\Specialized\ResponseType.cshtml"
                                      Write($@"{{""t"":18,".GetAsciiStringAsLong());

            
            #line default
            #line hidden
WriteLiteral("\r\n        public const int Total = 8;\r\n    }\r\n\r\n       public static class ");


            
            #line 33 "..\..\CodeGen\Specialized\ResponseType.cshtml"
                       Write("ExtensionsFor" + EnumName);

            
            #line default
            #line hidden
WriteLiteral(" {\r\n            public static bool IsError(this ResponseType rtype){\r\n           " +
"      switch( rtype ){\r\n");


            
            #line 36 "..\..\CodeGen\Specialized\ResponseType.cshtml"
                    foreach( var k in Enums.Keys.Where(k => k.EndsWith("ERROR")) ) { 

            
            #line default
            #line hidden
WriteLiteral("                        ");

WriteLiteral("case ResponseType.");


            
            #line 37 "..\..\CodeGen\Specialized\ResponseType.cshtml"
                                       Write(k);

            
            #line default
            #line hidden
WriteLiteral(":\r\n");



WriteLiteral("                            ");

WriteLiteral("return true;\r\n");


            
            #line 39 "..\..\CodeGen\Specialized\ResponseType.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    default:\r\n                        return false;\r\n            " +
"     }\r\n            }\r\n      }\r\n");


});

WriteLiteral("\r\n\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
