// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitleAttribute("RethinkDb Driver for .NET")]
[assembly: AssemblyProductAttribute("RethinkDb.Driver")]
[assembly: AssemblyCompanyAttribute("Brian Chavez")]
[assembly: AssemblyCopyrightAttribute("Brian Chavez © 2015")]
[assembly: AssemblyVersionAttribute("0.0.0")]
[assembly: AssemblyFileVersionAttribute("0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.0.0-localbuild built on 1/1/2015 12:00:00 AM")]
[assembly: AssemblyTrademarkAttribute("Modified Apache License v2.0")]
[assembly: AssemblyDescriptionAttribute("https://github.com/bchavez/RethinkDb.Driver")]
[assembly: InternalsVisibleToAttribute("Benchmark")]
[assembly: InternalsVisibleToAttribute("RethinkDb.Driver.Linq")]
[assembly: InternalsVisibleToAttribute("RethinkDb.Driver.Tests")]
[assembly: InternalsVisibleToAttribute("RethinkDb.Driver.Linq.Tests")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "RethinkDb Driver for .NET";
        internal const System.String AssemblyProduct = "RethinkDb.Driver";
        internal const System.String AssemblyCompany = "Brian Chavez";
        internal const System.String AssemblyCopyright = "Brian Chavez © 2015";
        internal const System.String AssemblyVersion = "0.0.0";
        internal const System.String AssemblyFileVersion = "0.0.0";
        internal const System.String AssemblyInformationalVersion = "0.0.0-localbuild built on 1/1/2015 12:00:00 AM";
        internal const System.String AssemblyTrademark = "Modified Apache License v2.0";
        internal const System.String AssemblyDescription = "https://github.com/bchavez/RethinkDb.Driver";
        internal const System.String InternalsVisibleTo = "Benchmark";
        internal const System.String InternalsVisibleTo_1 = "RethinkDb.Driver.Linq";
        internal const System.String InternalsVisibleTo_2 = "RethinkDb.Driver.Tests";
        internal const System.String InternalsVisibleTo_3 = "RethinkDb.Driver.Linq.Tests";
    }
}
