// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("RethinkDb Driver for .NET")]
[assembly: AssemblyProductAttribute("RethinkDb.Driver")]
[assembly: AssemblyCompanyAttribute("Brian Chavez")]
[assembly: AssemblyCopyrightAttribute("Brian Chavez © 2016")]
[assembly: AssemblyVersionAttribute("0.0.0")]
[assembly: AssemblyFileVersionAttribute("0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.0.0-localbuild built on 5/20/2016 6:35:21 AM")]
[assembly: AssemblyTrademarkAttribute("Apache License v2.0")]
[assembly: AssemblyDescriptionAttribute("http://www.github.com/bchavez/RethinkDb.Driver")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.0";
    }
}
