#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Templates
{
    using System;
    
    #line 1 "..\..\GlobalOptions.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 2 "..\..\GlobalOptions.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 3 "..\..\GlobalOptions.cshtml"
    using Humanizer;
    
    #line default
    #line hidden
    
    #line 4 "..\..\GlobalOptions.cshtml"
    using Newtonsoft.Json.Linq;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class GlobalOptions : Templates.BaseTemplate
    {
#line hidden

        #line 8 "..\..\GlobalOptions.cshtml"


    public Dictionary<string,string> OptArgs { get; set; }

    public string ReqlToNativeType(string reqlType)
    {
        if( reqlType.StartsWith("E") )
            return "string";
        if( reqlType == "T_BOOL" )
            return "bool?";
        if( reqlType == "T_NUM" )
            return "double?";
        if( reqlType == "T_STR" )
            return "string";

        return "object";
    }

        #line default
        #line hidden

        public override void Execute()
        {




WriteLiteral("\r\n");


WriteLiteral("\r\n");


WriteLiteral("\r\n\r\n//AUTOGENERATED, DO NOTMODIFY.\r\n//Do not edit this file directly.\r\n\r\nnamespac" +
"e RethinkDb.Driver.Model {\r\n    public class GlobalOptions {\r\n        \r\n");


            
            #line 33 "..\..\GlobalOptions.cshtml"
         foreach( var kvp in OptArgs )
        {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("public ");


            
            #line 35 "..\..\GlobalOptions.cshtml"
                Write(ReqlToNativeType(kvp.Value));

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 35 "..\..\GlobalOptions.cshtml"
                                             Write(Property(kvp.Key));

            
            #line default
            #line hidden
WriteLiteral(" { get; set; }\r\n");


            
            #line 36 "..\..\GlobalOptions.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n        public OptArgs toOptArgs(){\r\n             var ret = new OptArgs();\r\n   " +
"         \r\n");


            
            #line 41 "..\..\GlobalOptions.cshtml"
             foreach( var kvp in OptArgs )
            {

            
            #line default
            #line hidden
WriteLiteral("                 ");

WriteLiteral("if( this.");


            
            #line 43 "..\..\GlobalOptions.cshtml"
                       Write(Property(kvp.Key));

            
            #line default
            #line hidden
WriteLiteral(" != null )\r\n");



WriteLiteral("                    ");

WriteLiteral("ret.with(\"");


            
            #line 44 "..\..\GlobalOptions.cshtml"
                           Write(kvp.Key);

            
            #line default
            #line hidden
WriteLiteral("\", this.");


            
            #line 44 "..\..\GlobalOptions.cshtml"
                                           Write(Property(kvp.Key));

            
            #line default
            #line hidden
WriteLiteral(");\r\n");


            
            #line 45 "..\..\GlobalOptions.cshtml"
             
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n            return ret;\r\n        }\r\n\r\n        \r\n");


            
            #line 52 "..\..\GlobalOptions.cshtml"
         foreach( var kvp in OptArgs )
        {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("public static GlobalOptions ");


            
            #line 54 "..\..\GlobalOptions.cshtml"
                                      Write("with"+Class(kvp.Key));

            
            #line default
            #line hidden
WriteLiteral(" (");


            
            #line 54 "..\..\GlobalOptions.cshtml"
                                                               Write(ReqlToNativeType(kvp.Value));

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 54 "..\..\GlobalOptions.cshtml"
                                                                                            Write(Argument(kvp.Key ));

            
            #line default
            #line hidden
WriteLiteral(" ){\r\n");



WriteLiteral("                ");

WriteLiteral("return new GlobalOptions{ ");


            
            #line 55 "..\..\GlobalOptions.cshtml"
                                        Write(Property(kvp.Key) + " = " + Argument(kvp.Key));

            
            #line default
            #line hidden
WriteLiteral(" };\r\n");



WriteLiteral("            ");

WriteLiteral("}\r\n");


            
            #line 57 "..\..\GlobalOptions.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    \r\n    }\r\n}\r\n");


        }
    }
}
#pragma warning restore 1591
