#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Templates.CodeGen
{
    using System;
    
    #line 2 "..\..\CodeGen\AstSubclassTemplate.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 3 "..\..\CodeGen\AstSubclassTemplate.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 4 "..\..\CodeGen\AstSubclassTemplate.cshtml"
    using Humanizer;
    
    #line default
    #line hidden
    
    #line 5 "..\..\CodeGen\AstSubclassTemplate.cshtml"
    using Newtonsoft.Json.Linq;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class AstSubclassTemplate : Templates.BaseTemplate
    {
#line hidden

        #line 9 "..\..\CodeGen\AstSubclassTemplate.cshtml"

    public string ClassName { get; set; }
    public string Superclass { get; set; }
    public string IncludeIn { get; set; }

    public IEnumerable<KeyValuePair<string, JObject>> SpeicalMethods
    {
        get
        {
            return Meta.Where(kvp => kvp.Value["include_in"]?.Values<string>().Contains(this.IncludeIn) ?? false);
        }
    }

    public string TermType { get; set; }
    public Dictionary<string,JObject> Meta { get; set; }


        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");





WriteLiteral("\r\n");


WriteLiteral("\r\n");


WriteLiteral(@"

//AUTOGENERATED, DO NOTMODIFY.
//Do not edit this file directly.

// ReSharper disable CheckNamespace

using RethinkDb.Driver.Ast;
using RethinkDb.Driver.Model;
using RethinkDb.Driver.Proto;

namespace RethinkDb.Driver.Ast {
    public class ");


            
            #line 37 "..\..\CodeGen\AstSubclassTemplate.cshtml"
            Write(Class(ClassName));

            
            #line default
            #line hidden
WriteLiteral(" : ");


            
            #line 37 "..\..\CodeGen\AstSubclassTemplate.cshtml"
                                Write(Superclass);

            
            #line default
            #line hidden
WriteLiteral(" {\r\n    \r\n");


            
            #line 39 "..\..\CodeGen\AstSubclassTemplate.cshtml"
     if( this.TermType != null )
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("public ");


            
            #line 41 "..\..\CodeGen\AstSubclassTemplate.cshtml"
            Write(Class(ClassName));

            
            #line default
            #line hidden
WriteLiteral(" (object arg) : this(new Arguments(arg), null) {\r\n");



WriteLiteral("        ");

WriteLiteral("}\r\n");



WriteLiteral("        ");

WriteLiteral("public ");


            
            #line 43 "..\..\CodeGen\AstSubclassTemplate.cshtml"
            Write(Class(ClassName));

            
            #line default
            #line hidden
WriteLiteral(" (Arguments args, OptArgs optargs) : this(null, args, optargs) {\r\n");



WriteLiteral("        ");

WriteLiteral("}\r\n");



WriteLiteral("        ");

WriteLiteral("public ");


            
            #line 45 "..\..\CodeGen\AstSubclassTemplate.cshtml"
            Write(Class(ClassName));

            
            #line default
            #line hidden
WriteLiteral(" (ReqlAst prev, Arguments args, OptArgs optargs)\r\n");



WriteLiteral("        ");

WriteLiteral("     : this(prev, TermType.");


            
            #line 46 "..\..\CodeGen\AstSubclassTemplate.cshtml"
                                Write(TermType);

            
            #line default
            #line hidden
WriteLiteral(", args, optargs) {\r\n");



WriteLiteral("        ");

WriteLiteral("}\r\n");


            
            #line 48 "..\..\CodeGen\AstSubclassTemplate.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n        protected ");


            
            #line 50 "..\..\CodeGen\AstSubclassTemplate.cshtml"
             Write(Class(ClassName));

            
            #line default
            #line hidden
WriteLiteral(" (ReqlAst previous, TermType termType, Arguments args, OptArgs optargs) : base(pr" +
"evious, termType, args, optargs)\r\n        {\r\n        }\r\n\r\n    /* Static Factorie" +
"s */\r\n");


            
            #line 55 "..\..\CodeGen\AstSubclassTemplate.cshtml"
     if( this.TermType != null )
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("public static ");


            
            #line 57 "..\..\CodeGen\AstSubclassTemplate.cshtml"
                   Write(Class(ClassName));

            
            #line default
            #line hidden
WriteLiteral(" FromArgs(params object[] args){\r\n");



WriteLiteral("              ");

WriteLiteral(" return new ");


            
            #line 58 "..\..\CodeGen\AstSubclassTemplate.cshtml"
                       Write(Class(ClassName));

            
            #line default
            #line hidden
WriteLiteral(" (new Arguments(args), null);\r\n");



WriteLiteral("        ");

WriteLiteral("}\r\n");


            
            #line 60 "..\..\CodeGen\AstSubclassTemplate.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    /* Special Methods */\r\n");


            
            #line 63 "..\..\CodeGen\AstSubclassTemplate.cshtml"
         foreach( var m in this.SpeicalMethods )
        {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("public ");


            
            #line 65 "..\..\CodeGen\AstSubclassTemplate.cshtml"
                Write(Class(m.Key.ToLower()));

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 65 "..\..\CodeGen\AstSubclassTemplate.cshtml"
                                         Write(Method(m.Value["sharp_alias"]?.ToString() ?? m.Key.ToLower()));

            
            #line default
            #line hidden
WriteLiteral(" (params object[] fields){\r\n");


            
            #line 66 "..\..\CodeGen\AstSubclassTemplate.cshtml"
                if( IncludeIn == "top" )
                {

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral("return new ");


            
            #line 68 "..\..\CodeGen\AstSubclassTemplate.cshtml"
                            Write(Class(m.Key.ToLower()));

            
            #line default
            #line hidden
WriteLiteral(" (null, new Arguments(fields), new OptArgs());\r\n");


            
            #line 69 "..\..\CodeGen\AstSubclassTemplate.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral("return new ");


            
            #line 72 "..\..\CodeGen\AstSubclassTemplate.cshtml"
                            Write(Class(m.Key.ToLower()));

            
            #line default
            #line hidden
WriteLiteral(" (this, new Arguments(fields), new OptArgs());\r\n");


            
            #line 73 "..\..\CodeGen\AstSubclassTemplate.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("}\r\n");


            
            #line 75 "..\..\CodeGen\AstSubclassTemplate.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n    }\r\n}\r\n");


        }
    }
}
#pragma warning restore 1591
