#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Templates.CodeGen
{
    using System;
    
    #line 1 "..\..\CodeGen\EnumTemplate.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 2 "..\..\CodeGen\EnumTemplate.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class EnumTemplate : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 4 "..\..\CodeGen\EnumTemplate.cshtml"

    public string EnumName { get; set; }
    public Dictionary<string, object> Enums { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral("\r\n\r\n//AUTOGENERATED, DO NOTMODIFY.\r\n//Do not edit this file directly.\r\n\r\n// ReSha" +
"rper disable CheckNamespace\r\n\r\nnamespace RethinkDb.Driver.Proto {\r\n    public en" +
"um ");


            
            #line 15 "..\..\CodeGen\EnumTemplate.cshtml"
           Write(EnumName);

            
            #line default
            #line hidden
WriteLiteral(" {\r\n");


            
            #line 16 "..\..\CodeGen\EnumTemplate.cshtml"
     foreach( var kvp in this.Enums )
    {

            
            #line default
            #line hidden
WriteLiteral("        ");


            
            #line 18 "..\..\CodeGen\EnumTemplate.cshtml"
     Write(kvp.Key);

            
            #line default
            #line hidden
WriteLiteral(" = ");


            
            #line 18 "..\..\CodeGen\EnumTemplate.cshtml"
                Write(kvp.Value);

            
            #line default
            #line hidden
WriteLiteral(",\r\n");


            
            #line 19 "..\..\CodeGen\EnumTemplate.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    }\r\n\r\n");


            
            #line 22 "..\..\CodeGen\EnumTemplate.cshtml"
     if( EnumName == "ResponseNote" )
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("public static class ");


            
            #line 24 "..\..\CodeGen\EnumTemplate.cshtml"
                          Write("ExtensionsFor" + EnumName);

            
            #line default
            #line hidden
WriteLiteral(" {\r\n");



WriteLiteral("            ");

WriteLiteral("public static bool IsFeed(this ResponseNote note){\r\n");



WriteLiteral("                ");

WriteLiteral(" switch( note ){\r\n");


            
            #line 27 "..\..\CodeGen\EnumTemplate.cshtml"
                foreach( var k in Enums.Keys.Where(k => k.EndsWith("FEED") ))
                {

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral(" case ResponseNote.");


            
            #line 29 "..\..\CodeGen\EnumTemplate.cshtml"
                                    Write(k);

            
            #line default
            #line hidden
WriteLiteral(":\r\n");



WriteLiteral("                        ");

WriteLiteral("return true;\r\n");


            
            #line 31 "..\..\CodeGen\EnumTemplate.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral("default:\r\n");



WriteLiteral("                        ");

WriteLiteral("return false;\r\n");



WriteLiteral("                ");

WriteLiteral("}\r\n");



WriteLiteral("            ");

WriteLiteral("}\r\n");



WriteLiteral("        ");

WriteLiteral("}\r\n");


            
            #line 37 "..\..\CodeGen\EnumTemplate.cshtml"
    }

            
            #line default
            #line hidden

            
            #line 38 "..\..\CodeGen\EnumTemplate.cshtml"
     if( EnumName == "ResponseType" )
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("public static class ");


            
            #line 40 "..\..\CodeGen\EnumTemplate.cshtml"
                          Write("ExtensionsFor" + EnumName);

            
            #line default
            #line hidden
WriteLiteral(" {\r\n");



WriteLiteral("            ");

WriteLiteral("public static bool IsError(this ResponseType t){\r\n");



WriteLiteral("                ");

WriteLiteral(" switch( t ){\r\n");


            
            #line 43 "..\..\CodeGen\EnumTemplate.cshtml"
                foreach( var k in Enums.Keys.Where(k => k.EndsWith("ERROR")) )
                {

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral(" case ResponseType.");


            
            #line 45 "..\..\CodeGen\EnumTemplate.cshtml"
                                    Write(k);

            
            #line default
            #line hidden
WriteLiteral(":\r\n");



WriteLiteral("                        ");

WriteLiteral("return true;\r\n");


            
            #line 47 "..\..\CodeGen\EnumTemplate.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral("default:\r\n");



WriteLiteral("                        ");

WriteLiteral("return false;\r\n");



WriteLiteral("                ");

WriteLiteral("}\r\n");



WriteLiteral("            ");

WriteLiteral("}\r\n");



WriteLiteral("        ");

WriteLiteral("}\r\n");


            
            #line 53 "..\..\CodeGen\EnumTemplate.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n}\r\n");


        }
    }
}
#pragma warning restore 1591
