#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Templates.CodeGen
{
    using System;
    
    #line 1 "..\..\CodeGen\ExceptionTemplate.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 2 "..\..\CodeGen\ExceptionTemplate.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 3 "..\..\CodeGen\ExceptionTemplate.cshtml"
    using Humanizer;
    
    #line default
    #line hidden
    
    #line 4 "..\..\CodeGen\ExceptionTemplate.cshtml"
    using Newtonsoft.Json.Linq;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class ExceptionTemplate : Templates.CodeGen.BaseTemplate
    {
#line hidden

        #line 8 "..\..\CodeGen\ExceptionTemplate.cshtml"


    public string ClassName { get; set; }
    public string SuperClass { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {




WriteLiteral("\r\n");


WriteLiteral("\r\n");


WriteLiteral("\r\n\r\n//AUTOGENERATED, DO NOTMODIFY.\r\n//Do not edit this file directly.\r\n\r\n// ReSha" +
"rper disable CheckNamespace\r\n\r\nusing System;\r\nusing RethinkDb.Driver.Model;\r\nusi" +
"ng RethinkDb.Driver.Ast;\r\n\r\nnamespace RethinkDb.Driver {\r\n    public class ");


            
            #line 24 "..\..\CodeGen\ExceptionTemplate.cshtml"
            Write(Class(ClassName));

            
            #line default
            #line hidden
WriteLiteral(" : ");


            
            #line 24 "..\..\CodeGen\ExceptionTemplate.cshtml"
                                Write(Class(SuperClass));

            
            #line default
            #line hidden
WriteLiteral(" {\r\n\r\n");


            
            #line 26 "..\..\CodeGen\ExceptionTemplate.cshtml"
         if( ClassName == "reql_error" && SuperClass == "Exception" )
        {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("public Backtrace Backtrace { get; set; }\r\n");



WriteLiteral("            ");

WriteLiteral("public ReqlAst Term { get; set; }\r\n");


            
            #line 30 "..\..\CodeGen\ExceptionTemplate.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n        public ");


            
            #line 32 "..\..\CodeGen\ExceptionTemplate.cshtml"
          Write(Class(ClassName));

            
            #line default
            #line hidden
WriteLiteral(" () {\r\n        }\r\n\r\n        public ");


            
            #line 35 "..\..\CodeGen\ExceptionTemplate.cshtml"
          Write(Class(ClassName));

            
            #line default
            #line hidden
WriteLiteral(" (Exception e) : this(e.Message, e) {\r\n        }\r\n\r\n        public ");


            
            #line 38 "..\..\CodeGen\ExceptionTemplate.cshtml"
          Write(Class(ClassName));

            
            #line default
            #line hidden
WriteLiteral(" (string message) : base(message)\r\n        {\r\n        }\r\n\r\n        public ");


            
            #line 42 "..\..\CodeGen\ExceptionTemplate.cshtml"
          Write(Class(ClassName));

            
            #line default
            #line hidden
WriteLiteral(" (string message, Exception innerException) : base(message, innerException)\r\n    " +
"    {\r\n        }\r\n        \r\n        \r\n    }\r\n}\r\n");


        }
    }
}
#pragma warning restore 1591
