#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Templates.CodeGen
{
    using System;
    
    #line 1 "..\..\CodeGen\ReqlFunctionTemplate.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 2 "..\..\CodeGen\ReqlFunctionTemplate.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 3 "..\..\CodeGen\ReqlFunctionTemplate.cshtml"
    using Humanizer;
    
    #line default
    #line hidden
    
    #line 4 "..\..\CodeGen\ReqlFunctionTemplate.cshtml"
    using Newtonsoft.Json.Linq;
    
    #line default
    #line hidden
    
    #line 5 "..\..\CodeGen\ReqlFunctionTemplate.cshtml"
    using Templates.CodeGen.Util;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class ReqlFunctionTemplate : Templates.CodeGen.BaseTemplate
    {
#line hidden

        #line 9 "..\..\CodeGen\ReqlFunctionTemplate.cshtml"

    public int Arity { get; set; }


        #line default
        #line hidden

        public override void Execute()
        {





WriteLiteral("\r\n");


WriteLiteral("\r\n");


WriteLiteral(@"

//AUTOGENERATED, DO NOTMODIFY.
//Do not edit this file directly.

#pragma warning disable 1591
// ReSharper disable CheckNamespace

using System;
using RethinkDb.Driver.Model;
using RethinkDb.Driver.Ast;

namespace RethinkDb.Driver.Ast {
    public interface ");


            
            #line 25 "..\..\CodeGen\ReqlFunctionTemplate.cshtml"
                 Write("ReqlFunction"+Arity);

            
            #line default
            #line hidden
WriteLiteral(" : ReqlLambda{\r\n");


            
            #line 26 "..\..\CodeGen\ReqlFunctionTemplate.cshtml"
          
            var param = Enumerable.Range(1, Arity).Select(n => $"ReqlExpr arg{n}");
        

            
            #line default
            #line hidden
WriteLiteral("         object apply( ");


            
            #line 29 "..\..\CodeGen\ReqlFunctionTemplate.cshtml"
                  Write(string.Join(", ", param));

            
            #line default
            #line hidden
WriteLiteral(" );\r\n    }\r\n}\r\n");


        }
    }
}
#pragma warning restore 1591
