#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Templates.CodeGen
{
    
    #line 1 "..\..\CodeGen\TestTemplate.cshtml"
    using System;
    
    #line default
    #line hidden
    
    #line 2 "..\..\CodeGen\TestTemplate.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 3 "..\..\CodeGen\TestTemplate.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 4 "..\..\CodeGen\TestTemplate.cshtml"
    using Humanizer;
    
    #line default
    #line hidden
    
    #line 5 "..\..\CodeGen\TestTemplate.cshtml"
    using Newtonsoft.Json;
    
    #line default
    #line hidden
    
    #line 6 "..\..\CodeGen\TestTemplate.cshtml"
    using Newtonsoft.Json.Linq;
    
    #line default
    #line hidden
    
    #line 7 "..\..\CodeGen\TestTemplate.cshtml"
    using NUnit.Framework.Constraints;
    
    #line default
    #line hidden
    
    #line 8 "..\..\CodeGen\TestTemplate.cshtml"
    using Templates;
    
    #line default
    #line hidden
    
    #line 9 "..\..\CodeGen\TestTemplate.cshtml"
    using Templates.CodeGen.Util;
    
    #line default
    #line hidden
    
    #line 10 "..\..\CodeGen\TestTemplate.cshtml"
    using Templates.Metadata;
    
    #line default
    #line hidden
    
    #line 11 "..\..\CodeGen\TestTemplate.cshtml"
    using Z.ExtensionMethods;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class TestTemplate : Templates.CodeGen.BaseTemplate
    {
#line hidden

        #line 15 "..\..\CodeGen\TestTemplate.cshtml"

    public YamlTest YamlTest { get; set; }
    protected List<string> renderedVars = new List<string>();

        #line default
        #line hidden

        public override void Execute()
        {











WriteLiteral("\r\n");


WriteLiteral("\r\n");


WriteLiteral(@"


//AUTOGENERATED, DO NOTMODIFY.
//Do not edit this file directly.

#pragma warning disable 1591
// ReSharper disable CheckNamespace

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using RethinkDb.Driver.Model;
using RethinkDb.Driver.Ast;
using NUnit.Framework;
using RethinkDb.Driver.Tests;
using static RethinkDb.Driver.Tests.TestingCommon;

namespace RethinkDb.Driver.Test.Generated {

    // ");


            
            #line 39 "..\..\CodeGen\TestTemplate.cshtml"
  Write(YamlTest.Description);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    [TestFixture]\r\n    public class ");


            
            #line 42 "..\..\CodeGen\TestTemplate.cshtml"
            Write(YamlTest.ModuleName);

            
            #line default
            #line hidden
WriteLiteral(" : YamlTestFixture {\r\n\r\n        public ");


            
            #line 44 "..\..\CodeGen\TestTemplate.cshtml"
          Write(YamlTest.ModuleName);

            
            #line default
            #line hidden
WriteLiteral(" (){\r\n");


            
            #line 45 "..\..\CodeGen\TestTemplate.cshtml"
             foreach (var table in this.YamlTest.TableVarNames)
            {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("tableVars.Add( \"");


            
            #line 47 "..\..\CodeGen\TestTemplate.cshtml"
                             Write(table);

            
            #line default
            #line hidden
WriteLiteral("\" );\r\n");


            
            #line 48 "..\..\CodeGen\TestTemplate.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        }\r\n\r\n\r\n");


            
            #line 52 "..\..\CodeGen\TestTemplate.cshtml"
         foreach( var table in this.YamlTest.TableVarNames )
        {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("public static Table ");


            
            #line 54 "..\..\CodeGen\TestTemplate.cshtml"
                             Write(table);

            
            #line default
            #line hidden
WriteLiteral(" = r.db(DbName).table(\"");


            
            #line 54 "..\..\CodeGen\TestTemplate.cshtml"
                                                          Write(table);

            
            #line default
            #line hidden
WriteLiteral("\");\r\n");


            
            #line 55 "..\..\CodeGen\TestTemplate.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n        [Test]\r\n        public void YamlTest(){\r\n\r\n");


            
            #line 61 "..\..\CodeGen\TestTemplate.cshtml"
      foreach( var test in this.YamlTest.DefsAndTests )
     {
         if( test.TestType == "JavaDef" )
         {

            
            #line default
            #line hidden
WriteLiteral("             ");

WriteLiteral("\r\n");



WriteLiteral("             ");

WriteLiteral("//JavaDef, ");


            
            #line 66 "..\..\CodeGen\TestTemplate.cshtml"
                     Write(test.TestFile);

            
            #line default
            #line hidden
WriteLiteral(", #");


            
            #line 66 "..\..\CodeGen\TestTemplate.cshtml"
                                      Write(test.LineNum);

            
            #line default
            #line hidden
WriteLiteral("\r\n");



WriteLiteral("             ");

WriteLiteral("//Original: ");


            
            #line 67 "..\..\CodeGen\TestTemplate.cshtml"
                      Write(test.Original);

            
            #line default
            #line hidden
WriteLiteral("\r\n");



WriteLiteral("             ");

WriteLiteral("\r\n");


            
            #line 69 "..\..\CodeGen\TestTemplate.cshtml"
             if( @renderedVars.Contains(test.VarName) )
             {

            
            #line default
            #line hidden
WriteLiteral("                 ");


            
            #line 71 "..\..\CodeGen\TestTemplate.cshtml"
              Write(test.VarName);

            
            #line default
            #line hidden
WriteLiteral(" = ");


            
            #line 71 "..\..\CodeGen\TestTemplate.cshtml"
                               Write( test.RunIfQuery ? "maybeRun" : "");

            
            #line default
            #line hidden
WriteLiteral(" (");


            
            #line 71 "..\..\CodeGen\TestTemplate.cshtml"
                                                                     Write(test.Value);

            
            #line default
            #line hidden
WriteLiteral(");\r\n");


            
            #line 72 "..\..\CodeGen\TestTemplate.cshtml"
             }
             else if( test.RunIfQuery )
             {

            
            #line default
            #line hidden
WriteLiteral("                 ");

WriteLiteral("var ");


            
            #line 75 "..\..\CodeGen\TestTemplate.cshtml"
                  Write(test.VarName);

            
            #line default
            #line hidden
WriteLiteral(" = maybeRun( ");


            
            #line 75 "..\..\CodeGen\TestTemplate.cshtml"
                                            Write(test.Value);

            
            #line default
            #line hidden
WriteLiteral(" , conn, new {\r\n");


            
            #line 76 "..\..\CodeGen\TestTemplate.cshtml"
                 foreach (var opt in test.RunOpts)
                 {

            
            #line default
            #line hidden
WriteLiteral("                    ");


            
            #line 78 "..\..\CodeGen\TestTemplate.cshtml"
                 Write(opt.Key);

            
            #line default
            #line hidden
WriteLiteral(" = ");


            
            #line 78 "..\..\CodeGen\TestTemplate.cshtml"
                             Write(opt.Val.IsNumber(0) || opt.Val.IsNumber(1) ? opt.Val : $"\"{opt.Val}\"" );

            
            #line default
            #line hidden
WriteLiteral(" ,\r\n");


            
            #line 79 "..\..\CodeGen\TestTemplate.cshtml"
                 }

            
            #line default
            #line hidden
WriteLiteral("                 ");

WriteLiteral(" } );\r\n");


            
            #line 81 "..\..\CodeGen\TestTemplate.cshtml"
                 renderedVars.Add(@test.VarName);
             }
             else
             {

            
            #line default
            #line hidden
WriteLiteral("                 ");


            
            #line 85 "..\..\CodeGen\TestTemplate.cshtml"
               Write( test.VarType.Contains("ReqlFunction") ? test.VarType : "var" );

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 85 "..\..\CodeGen\TestTemplate.cshtml"
                                                                                Write(test.VarName);

            
            #line default
            #line hidden
WriteLiteral(" = ");


            
            #line 85 "..\..\CodeGen\TestTemplate.cshtml"
                                                                                                Write(test.Value);

            
            #line default
            #line hidden
WriteLiteral(";\r\n");


            
            #line 86 "..\..\CodeGen\TestTemplate.cshtml"
                 renderedVars.Add(@test.VarName);
             }

            
            #line default
            #line hidden
WriteLiteral("             ");

WriteLiteral("\r\n");


            
            #line 89 "..\..\CodeGen\TestTemplate.cshtml"
         }
         else if( test.TestType == "JavaQuery" )
         {

            
            #line default
            #line hidden
WriteLiteral("             ");

WriteLiteral("{\r\n");



WriteLiteral("                 ");

WriteLiteral("SetContext( \"");


            
            #line 93 "..\..\CodeGen\TestTemplate.cshtml"
                            Write(JsonConvert.SerializeObject(test).EncodeBase64());

            
            #line default
            #line hidden
WriteLiteral("\" );\r\n");



WriteLiteral("                 ");

WriteLiteral("//JavaQuery, ");


            
            #line 94 "..\..\CodeGen\TestTemplate.cshtml"
                           Write(test.TestFile);

            
            #line default
            #line hidden
WriteLiteral(", #");


            
            #line 94 "..\..\CodeGen\TestTemplate.cshtml"
                                            Write(test.LineNum);

            
            #line default
            #line hidden
WriteLiteral("\r\n");



WriteLiteral("                 ");

WriteLiteral("/* ExpectedOriginal: ");


            
            #line 95 "..\..\CodeGen\TestTemplate.cshtml"
                                   Write(test.ExpectedOriginal);

            
            #line default
            #line hidden
WriteLiteral(" */\r\n");



WriteLiteral("                 ");

WriteLiteral("var expected_ = ");


            
            #line 96 "..\..\CodeGen\TestTemplate.cshtml"
                               Write(test.ExpectedJava ?? "null as object");

            
            #line default
            #line hidden
WriteLiteral(";\r\n");



WriteLiteral("                 ");

WriteLiteral("\r\n");



WriteLiteral("                 ");

WriteLiteral("/* Original: ");


            
            #line 98 "..\..\CodeGen\TestTemplate.cshtml"
                           Write(test.Original);

            
            #line default
            #line hidden
WriteLiteral(" */\r\n");



WriteLiteral("                 ");

WriteLiteral("var obtained = runOrCatch( ");


            
            #line 99 "..\..\CodeGen\TestTemplate.cshtml"
                                         Write(test.Java);

            
            #line default
            #line hidden
WriteLiteral(" ,\r\n");



WriteLiteral("                 ");

WriteLiteral("                           new {\r\n");


            
            #line 101 "..\..\CodeGen\TestTemplate.cshtml"
                 foreach( var opt in test.RunOpts )
                 {

            
            #line default
            #line hidden
WriteLiteral("                     ");


            
            #line 103 "..\..\CodeGen\TestTemplate.cshtml"
                  Write(opt.Key);

            
            #line default
            #line hidden
WriteLiteral(" = ");


            
            #line 103 "..\..\CodeGen\TestTemplate.cshtml"
                              Write(opt.Val.IsNumber(0) || opt.Val.IsNumber(1) ?  opt.Val : $"\"{opt.Val}\"" );

            
            #line default
            #line hidden
WriteLiteral(" ,\r\n");


            
            #line 104 "..\..\CodeGen\TestTemplate.cshtml"
                 }

            
            #line default
            #line hidden
WriteLiteral("                 ");

WriteLiteral("   }, conn);\r\n");


            
            #line 106 "..\..\CodeGen\TestTemplate.cshtml"
                 

            
            #line default
            #line hidden
WriteLiteral("                 ");

WriteLiteral("\r\n");


            
            #line 108 "..\..\CodeGen\TestTemplate.cshtml"
                 if( @test.ExpectedType.EndsWith("[]") )
                 {

            
            #line default
            #line hidden
WriteLiteral("                     ");

WriteLiteral("assertArrayEquals(expected_, obtained);\r\n");


            
            #line 111 "..\..\CodeGen\TestTemplate.cshtml"
                 }
                 else if( test.ExpectedType == "double" )
                 {

            
            #line default
            #line hidden
WriteLiteral("                     ");

WriteLiteral("assertEquals((double) expected_, (double) obtained, 0.00000000001);\r\n");


            
            #line 115 "..\..\CodeGen\TestTemplate.cshtml"
                 }
                 else
                 {

            
            #line default
            #line hidden
WriteLiteral("                     ");

WriteLiteral("assertEquals(expected_, obtained);                 \r\n");


            
            #line 119 "..\..\CodeGen\TestTemplate.cshtml"
                 }

            
            #line default
            #line hidden
WriteLiteral("             ");

WriteLiteral("}\r\n");



WriteLiteral("             ");

WriteLiteral("\r\n");


            
            #line 122 "..\..\CodeGen\TestTemplate.cshtml"
         }
     }

            
            #line default
            #line hidden
WriteLiteral("\r\n        }\r\n    }\r\n}\r\n");


        }
    }
}
#pragma warning restore 1591
