#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Templates.CodeGen
{
    using System;
    
    #line 1 "..\..\CodeGen\TestTemplate.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 2 "..\..\CodeGen\TestTemplate.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 3 "..\..\CodeGen\TestTemplate.cshtml"
    using Humanizer;
    
    #line default
    #line hidden
    
    #line 4 "..\..\CodeGen\TestTemplate.cshtml"
    using Newtonsoft.Json.Linq;
    
    #line default
    #line hidden
    
    #line 5 "..\..\CodeGen\TestTemplate.cshtml"
    using Templates;
    
    #line default
    #line hidden
    
    #line 6 "..\..\CodeGen\TestTemplate.cshtml"
    using Templates.CodeGen.Util;
    
    #line default
    #line hidden
    
    #line 7 "..\..\CodeGen\TestTemplate.cshtml"
    using Templates.Metadata;
    
    #line default
    #line hidden
    
    #line 8 "..\..\CodeGen\TestTemplate.cshtml"
    using Z.ExtensionMethods;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class TestTemplate : Templates.CodeGen.BaseTemplate
    {
#line hidden

        #line 12 "..\..\CodeGen\TestTemplate.cshtml"

    public YamlTest YamlTest { get; set; }


        #line default
        #line hidden

        public override void Execute()
        {








WriteLiteral("\r\n");


WriteLiteral("\r\n");


WriteLiteral(@"


//AUTOGENERATED, DO NOTMODIFY.
//Do not edit this file directly.

#pragma warning disable 1591
// ReSharper disable CheckNamespace

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using RethinkDb.Driver.Model;
using RethinkDb.Driver.Ast;
using NUnit.Framework;
using RethinkDb.Driver.Tests;

namespace RethinkDb.Driver.Test.Generated {
    [TestFixture]
    public class ");


            
            #line 35 "..\..\CodeGen\TestTemplate.cshtml"
            Write(YamlTest.ModuleName);

            
            #line default
            #line hidden
WriteLiteral(" : GeneratedTest {\r\n\r\n");


            
            #line 37 "..\..\CodeGen\TestTemplate.cshtml"
         foreach( var table in this.YamlTest.TableVarNames )
        {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("public static Table ");


            
            #line 39 "..\..\CodeGen\TestTemplate.cshtml"
                             Write(table);

            
            #line default
            #line hidden
WriteLiteral(" = r.db(DbName).table(\"");


            
            #line 39 "..\..\CodeGen\TestTemplate.cshtml"
                                                          Write(table);

            
            #line default
            #line hidden
WriteLiteral("\");\r\n");


            
            #line 40 "..\..\CodeGen\TestTemplate.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n        [Test]\r\n        public void YamlTest(){\r\n\r\n");


            
            #line 46 "..\..\CodeGen\TestTemplate.cshtml"
      foreach( var test in this.YamlTest.DefsAndTests )
     {
         if( test.TestType == "JavaDef" )
         {

            
            #line default
            #line hidden
WriteLiteral("             ");

WriteLiteral("\r\n");



WriteLiteral("             ");

WriteLiteral("//JavaDef, ");


            
            #line 51 "..\..\CodeGen\TestTemplate.cshtml"
                     Write(test.TestFile);

            
            #line default
            #line hidden
WriteLiteral(", #");


            
            #line 51 "..\..\CodeGen\TestTemplate.cshtml"
                                      Write(test);

            
            #line default
            #line hidden
WriteLiteral(".\r\n");



WriteLiteral("             ");

WriteLiteral("//Original: ");


            
            #line 52 "..\..\CodeGen\TestTemplate.cshtml"
                      Write(test.Original);

            
            #line default
            #line hidden
WriteLiteral("\r\n");



WriteLiteral("             ");

WriteLiteral("\r\n");


            
            #line 54 "..\..\CodeGen\TestTemplate.cshtml"
             
            
            #line default
            #line hidden
            
            #line 54 "..\..\CodeGen\TestTemplate.cshtml"
        Write(test.Java);

            
            #line default
            #line hidden
            
            #line 54 "..\..\CodeGen\TestTemplate.cshtml"
                       

            
            #line default
            #line hidden
WriteLiteral("             ");

WriteLiteral("\r\n");


            
            #line 56 "..\..\CodeGen\TestTemplate.cshtml"
         }
         else if( test.TestType == "JavaQuery" )
         {

            
            #line default
            #line hidden
WriteLiteral("             ");

WriteLiteral("TestCounter++;\r\n");



WriteLiteral("             ");

WriteLiteral("\r\n");



WriteLiteral("             ");

WriteLiteral("{\r\n");



WriteLiteral("                 ");

WriteLiteral("//JavaQuery, ");


            
            #line 62 "..\..\CodeGen\TestTemplate.cshtml"
                           Write(test.TestFile);

            
            #line default
            #line hidden
WriteLiteral(", #");


            
            #line 62 "..\..\CodeGen\TestTemplate.cshtml"
                                            Write(test.TestNum);

            
            #line default
            #line hidden
WriteLiteral("\r\n");



WriteLiteral("                 ");

WriteLiteral("/* ExpectedOriginal: ");


            
            #line 63 "..\..\CodeGen\TestTemplate.cshtml"
                                   Write(test.ExpectedOriginal);

            
            #line default
            #line hidden
WriteLiteral(" */\r\n");



WriteLiteral("                 ");

WriteLiteral("var expected_ = ");


            
            #line 64 "..\..\CodeGen\TestTemplate.cshtml"
                               Write(test.ExpectedJava ?? "null as object");

            
            #line default
            #line hidden
WriteLiteral(";\r\n");



WriteLiteral("                 ");

WriteLiteral("\r\n");



WriteLiteral("                 ");

WriteLiteral("/* Original: ");


            
            #line 66 "..\..\CodeGen\TestTemplate.cshtml"
                           Write(test.Original);

            
            #line default
            #line hidden
WriteLiteral(" */\r\n");



WriteLiteral("                 ");

WriteLiteral("var obtained = runOrCatch( ");


            
            #line 67 "..\..\CodeGen\TestTemplate.cshtml"
                                         Write(test.Java);

            
            #line default
            #line hidden
WriteLiteral(" ,\r\n");



WriteLiteral("                 ");

WriteLiteral("                           new OptArgs()\r\n");


            
            #line 69 "..\..\CodeGen\TestTemplate.cshtml"
                 foreach( var opt in test.RunOpts )
                 {

            
            #line default
            #line hidden
WriteLiteral("                     ");

WriteLiteral(".with(\"");


            
            #line 71 "..\..\CodeGen\TestTemplate.cshtml"
                         Write(opt.Key);

            
            #line default
            #line hidden
WriteLiteral("\", ");


            
            #line 71 "..\..\CodeGen\TestTemplate.cshtml"
                                     Write(opt.Val.IsNumber(0) || opt.Val.IsNumber(1) ?  opt.Val : "\"" + opt.Val + "\"" );

            
            #line default
            #line hidden
WriteLiteral(")\r\n");


            
            #line 72 "..\..\CodeGen\TestTemplate.cshtml"
                 }

            
            #line default
            #line hidden
WriteLiteral("                 ");

WriteLiteral("   );\r\n");


            
            #line 74 "..\..\CodeGen\TestTemplate.cshtml"
                 

            
            #line default
            #line hidden
WriteLiteral("                 ");

WriteLiteral("assertEquals(expected_, obtained);\r\n");



WriteLiteral("             ");

WriteLiteral("}\r\n");



WriteLiteral("             ");

WriteLiteral("\r\n");


            
            #line 78 "..\..\CodeGen\TestTemplate.cshtml"
         }
     }

            
            #line default
            #line hidden
WriteLiteral("\r\n        }\r\n    }\r\n}\r\n");


        }
    }
}
#pragma warning restore 1591
