


//AUTOGENERATED, DO NOTMODIFY.
//Do not edit this file directly.

namespace RethinkDb.Driver.Proto {
    public enum DatumType {
        R_NULL = 1,
        R_BOOL = 2,
        R_NUM = 3,
        R_STR = 4,
        R_ARRAY = 5,
        R_OBJECT = 6,
        R_JSON = 7,
    }


}
