


//AUTOGENERATED, DO NOTMODIFY.
//Do not edit this file directly.

namespace RethinkDb.Driver.Proto {
    public enum ErrorType {
        INTERNAL = 1000000,
        RESOURCE = 2000000,
        LOGIC = 3000000,
        NON_EXISTENCE = 3100000,
        OP_FAILED = 4100000,
        OP_INDETERMINATE = 4200000,
        USER = 5000000,
    }


}
